apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client-142
spec:
  nodeSelector:
    rdei.io/sec-zone-green: "true"
    kubernetes.io/hostname: "10.112.188.142"
  tolerations:
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: "NoExecute"
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node.kubernetes.io/unschedulable"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: iperf3-client-142
      image: hub.comcast.net/viper-qaperf/iperf3:latest
      imagePullPolicy: Always
      command: [ "sleep", "30000" ]
      resources:
        requests:
          memory: "32Gi"
          cpu: "32000m"
        limits:
          memory: "32Gi"
          cpu: "32000m"


# rdei.io/vperf-linear-01: true