apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server-135
  labels:
    app: iperf3-server-135
spec:
  nodeSelector:
    rdei.io/sec-zone-green: "true"
    rdei.io/vperf-linear-01: "true"
    kubernetes.io/hostname: "10.112.188.135"
  tolerations:
    - key: "rdei.io/vperf-linear-01"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
    - name: perf-server-container
      image: hub.comcast.net/viper-qaperf/iperf3:latest
      imagePullPolicy: Always
      command: [ "iperf3", "-s" ]
      ports:
        - containerPort: 5201
      resources:
        requests:
          memory: "32Gi"
          cpu: "32000m"
        limits:
          memory: "32Gi"
          cpu: "32000m"
