apiVersion: v1
kind: Service
metadata:
  name: iperf3-server-service-dell-32
  labels:
    app: iperf3-server-service-dell-32
spec:
  ports:
    - port: 5201
      protocol: TCP
      name: http
      targetPort: 5201
  selector:
    app: iperf3-server-dell-32
